# Generated by Django 3.0.3 on 2020-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='post_message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='registration_date',
        ),
        migrations.AddField(
            model_name='coach',
            name='sport_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
