# Generated by Django 3.0.3 on 2020-03-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20200226_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='cash',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
