# Generated by Django 3.0.3 on 2020-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20200401_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('card', models.IntegerField()),
            ],
        ),
    ]
